CREATE SCHEMA IF NOT EXISTS reports;

CREATE TABLE IF NOT EXISTS reports.click_count (
  date  DATE   NOT NULL UNIQUE,
  count BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS reports.domain_regex (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000  INCREMENT BY 1 ) PRIMARY KEY,
  pattern    VARCHAR(8000) UNIQUE,
  date_added TIMESTAMP,
  is_active  BOOLEAN
);

CREATE TABLE IF NOT EXISTS reports.tracked_domain_requests (
  date       DATE          NOT NULL,
  domain_id  BIGINT REFERENCES reports.domain_regex (id),
  address    VARCHAR(15)   NOT NULL,
  login      VARCHAR(8000) NOT NULL,
  first_time TIME          NOT NULL,
  last_time  TIME          NOT NULL,
  count      BIGINT        NOT NULL,
  CONSTRAINT unique_track UNIQUE (date, domain_id, address, login)
);
